services:
  notification_db:
    image: postgres:15
    environment:
    - POSTGRES_USER=admin
    - POSTGRES_PASSWORD=pypass
    - POSTGRES_DB=notification_db
    ports:
    - "5432:5432"
    volumes:
    - postgres_data:/var/lib/postgresql/data

  airflow_orchestator:
    build: .
    ports:
    - "8080:8080"
    environment:
    - DB_HOST=notification_db
    - DB_USER=admin
    - DB_PASSWORD=pypass
    - DB_NAME=notification_db
    # airflow connections
    - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://admin:pypass@notification_db/notification_db
    - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    - AIRFLOW__CORE__LOAD_EXAMPLES=False
    - AIRFLOW__CORE__DAGS_FOLDER=/app/dags
    - AIRFLOW_HOME=/app
    depends_on:
    - notification_db
    command: >
      bash -c "
      echo 'Waiting for postgres...' &&
      sleep 5 &&
      airflow db migrate &&
      airflow standalone" 
    volumes:  
    - .:/app
    # in prod envs, we make webserver and scehduler separate
  
  pgadmin:
    image: dpage/pgadmin4
    environment:
    - PGADMIN_DEFAULT_EMAIL=admin@admin.com
    - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
    - "8081:80"
    depends_on:
    - notification_db
    volumes:
    - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data: